// <auto-generated/>
// Simulated source-generator output for the find-implementations-source-gen-partial-dedup
// regression fixture. The .g.cs suffix is the signal ReferenceService uses to treat this
// declaration as generator-emitted and dedupe it against the user-authored partial.
namespace SampleLib.PartialImplFixture;

public partial class SnapshotStore
{
    // Intentionally empty. A real generator would add a [LoggerMessage]-derived method
    // or similar helper here. For the dedup test we only need the extra partial
    // declaration to exist at this file path.
}
