#!/usr/bin/env python3
"""One-pass intake-from-issues for open [audit] GH Issues → ai_docs/backlog.md rows.

Read-only against GitHub; mutates only ai_docs/backlog.md. Idempotent: re-running
after rows are already added produces duplicate row ids the planner will reject.

Generated by Claude as a one-off for the 2026-05-17 reconcile of un-intaked
audit Issues. Not part of the shipped surface — keep here for future audit
waves until a proper /intake-from-issues skill exists.
"""
import json
import subprocess
import re
import datetime
import sys
from pathlib import Path

REPO_PREFIXES = ('networkdocumentation-', 'tradewise-', 'firewallanalyzer-',
                 'itchatbot-', 'roslyn-backed-mcp-')
SEV_TO_PRI = {'P1': 'High', 'P2': 'Medium', 'P3': 'Low'}


def gh(*args):
    return subprocess.run(['gh', *args], capture_output=True, text=True, check=True).stdout


def extract_field(body, label):
    m = re.search(rf'\*\*{re.escape(label)}:\*\*\s*(.+?)(?:\n\n|\n\s*[-*]\s|\n##|\Z)',
                  body, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip().replace('\n', ' ')
    m = re.search(rf'(?:^|\n)\s*[-*]\s*\*?\*?{re.escape(label)}:?\*?\*?\s*(.+?)(?:\n\s*[-*]\s|\n##|\Z)',
                  body, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip().replace('\n', ' ')
    return None


def extract_section(body, heading):
    m = re.search(rf'(?:^|\n)##\s*{re.escape(heading)}\s*\n(.*?)(?=\n##|\Z)',
                  body, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip().replace('\n\n', ' / ').replace('\n', ' ')
    return None


def strip_repo_prefix(fid):
    for p in REPO_PREFIXES:
        if fid.startswith(p):
            return fid[len(p):]
    return fid


def collapse(s, n=400):
    s = re.sub(r'\s+', ' ', s).strip()
    if len(s) > n:
        s = s[:n - 1].rsplit(' ', 1)[0] + '...'
    return s


def main():
    issues = json.loads(gh('issue', 'list', '--state=open',
                           '--search', 'in:title [audit]',
                           '--limit', '50',
                           '--json', 'number,title,body'))

    rows_by_pri = {'High': [], 'Medium': [], 'Low': []}
    errors = []
    for i in issues:
        n = i['number']
        body = i['body'] or ''
        title = i['title']
        display_title = re.sub(r'^\[audit\]\s*', '', title)

        fid_raw = None
        for p in [r'\*\*id:\*\*\s*`?([a-z][-a-z0-9]+)`?',
                  r'(?:^|\n)\s*[-*]?\s*id:\s*`?([a-z][-a-z0-9]{5,})`?']:
            m = re.search(p, body, re.MULTILINE)
            if m:
                fid_raw = m.group(1)
                break
        if not fid_raw:
            fid_raw = re.sub(r'[^a-z0-9]+', '-', display_title.lower()).strip('-')[:60]
        fid = strip_repo_prefix(fid_raw)

        severity = extract_field(body, 'severity')
        if severity:
            severity = severity.split()[0].upper().rstrip('.,:')
        pri = SEV_TO_PRI.get(severity)
        if not pri:
            errors.append(f'#{n} skipped (no severity parsed)')
            continue

        server_version = (extract_field(body, 'Server version')
                          or extract_field(body, 'server_version') or '?')
        report = (extract_field(body, 'Report')
                  or extract_field(body, 'source_audit') or '')
        anchors = (extract_field(body, 'Anchors')
                   or extract_field(body, 'anchors') or '')

        finding = extract_section(body, 'Finding') or display_title
        fix = (extract_section(body, 'Proposed fix')
               or extract_section(body, 'Proposed Fix') or '')

        url = f'https://github.com/darylmcd/Roslyn-Backed-MCP/issues/{n}'
        parts = [f'[gh #{n}]({url}): {collapse(finding, 350)}']
        if fix:
            parts.append(f'Fix: {collapse(fix, 300)}')
        if anchors:
            parts.append(f'Anchors: {collapse(anchors, 200)}')
        parts.append(f'Regression test shape: 1 fixture covering the repro scenario from gh #{n}.')
        evidence = f'gh #{n}'
        if report:
            evidence += f'; {collapse(report, 120)}'
        if server_version != '?':
            evidence += f'; observed on roslyn-mcp {server_version}'
        parts.append(f'Evidence: {evidence}.')

        do = ' '.join(parts).replace('|', '\\|')
        rows_by_pri[pri].append((n, f'| `{fid}` | {pri} | none | {do} |'))

    for k in rows_by_pri:
        rows_by_pri[k].sort(key=lambda r: r[0])
    rows_flat = {k: [r[1] for r in v] for k, v in rows_by_pri.items()}

    # Hard-coded aggregator rows for the two firewallanalyzer polish-list issues
    rows_flat['Medium'].append(
        '| `firewallanalyzer-p2-polish-aggregate-20260516` | Medium | none | '
        '[gh #768](https://github.com/darylmcd/Roslyn-Backed-MCP/issues/768): '
        'Aggregator row - 11 P2 findings from the 2026-05-16 firewallanalyzer surface-test '
        '(sections 13.3, 13.9-13.18). Each finding is independent and should be split '
        'into its own row when a maintainer claims it; this row tracks intake-completeness only. '
        'Findings span: static-extension-host cross-tool blind spot, code_fix_preview vs fix_all_preview '
        'shape inconsistency, suggest_refactorings facade-pattern recommendation, find_duplicated_methods '
        'symmetric-mapper false positives, test_coverage fail-fast on missing coverlet, '
        'set_conditional_property_preview allowlist narrowness, get_completions filterText ranking gap, '
        'semantic_grep dotted-identifier tokenization docs gap, get_di_registrations multi-registration '
        'overcounting, migrate_package_preview no-op silent mutation, scaffold_first_test_file_preview '
        'single-target heuristic. Anchors: per-finding in gh #768 body. Regression test shape: '
        '1 fixture per split row. Evidence: gh #768; audit-reports/20260516T062913Z_firewallanalyzer_mcp-server-surface-test.md. |'
    )
    rows_flat['Low'].append(
        '| `firewallanalyzer-p3-polish-aggregate-20260516` | Low | none | '
        '[gh #769](https://github.com/darylmcd/Roslyn-Backed-MCP/issues/769): '
        'Aggregator row - 8 P3 cosmetic/UX/docs-gap findings from the 2026-05-16 firewallanalyzer '
        'surface-test (sections 13.19-13.26). Each finding is independent and should be split '
        'into its own row when a maintainer claims it; this row tracks intake-completeness only. '
        'Findings span: find_duplicate_helpers framework-wrapper filter leak, document_symbols vs '
        'symbol_info record-kind disagreement, compile_check file-filter scope-narrowing inconsistency, '
        'get_nuget_dependencies(summary=true) CPM literal, get_cohesion_metrics always-null lifecyclePattern, '
        'add_pragma_suppression CRLF in LF file, get_msbuild_properties vs workspace_reload OutputType '
        'mismatch, source_file_lines off-by-one marker count. Anchors: per-finding in gh #769 body. '
        'Regression test shape: 1 fixture per split row. Evidence: gh #769; audit-reports/20260516T062913Z_firewallanalyzer_mcp-server-surface-test.md. |'
    )

    repo_root = Path(__file__).resolve().parent.parent
    backlog_path = repo_root / 'ai_docs' / 'backlog.md'
    backlog = backlog_path.read_text(encoding='utf-8')

    def insert_after_table_header(content, section, new_rows):
        pattern = re.compile(
            rf'(##\s*{re.escape(section)}\s*\n(?:[^\n]*\n)*?\|----\|-----\|------\|-----\|\n)',
            re.MULTILINE)
        m = pattern.search(content)
        if not m:
            raise RuntimeError(f'Could not find table header under ## {section}')
        insert_at = m.end()
        return content[:insert_at] + '\n'.join(new_rows) + '\n' + content[insert_at:]

    for pri in ('High', 'Medium', 'Low'):
        if rows_flat[pri]:
            backlog = insert_after_table_header(backlog, pri, rows_flat[pri])

    now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    backlog = re.sub(r'\*\*updated_at:[^*]+\*\*', f'**updated_at: {now}**', backlog)

    backlog_path.write_text(backlog, encoding='utf-8')

    print(f"Inserted: High={len(rows_flat['High'])} "
          f"Medium={len(rows_flat['Medium'])} "
          f"Low={len(rows_flat['Low'])}")
    print(f"Skipped {len(errors)}: {errors}")
    print(f"updated_at -> {now}")


if __name__ == '__main__':
    sys.exit(main())
