namespace RoslynMcp.Host.Stdio.Catalog;

public static partial class ServerSurfaceCatalog
{
    private static readonly SurfaceEntry[] AnalysisTools =
    [
        Tool("project_diagnostics", "analysis", "stable", true, false, "Return compiler diagnostics for a workspace."),
        Tool("diagnostic_details", "analysis", "stable", true, false, "Inspect one diagnostic occurrence in detail."),
        Tool("type_hierarchy", "analysis", "stable", true, false, "Inspect type inheritance and interface relationships."),
        Tool("callers_callees", "analysis", "stable", true, false, "Find direct callers and callees for a method."),
        Tool("impact_analysis", "analysis", "stable", true, false, "Estimate the impact of changing a symbol."),
        Tool("find_type_mutations", "analysis", "stable", true, false, "Identify mutating members of a type and who calls them."),
        Tool("find_type_usages", "analysis", "stable", true, false, "Classify usages of a type across the solution."),
        Tool("build_workspace", "validation", "stable", false, false, "Run dotnet build for the loaded workspace."),
        Tool("build_project", "validation", "stable", false, false, "Run dotnet build for a selected project."),
        Tool("test_discover", "validation", "stable", true, false, "Discover tests in the loaded workspace."),
        Tool("test_run", "validation", "stable", false, false, "Run dotnet test for the workspace or a selected project."),
        Tool("test_related", "validation", "stable", true, false, "Find tests related to a symbol."),
        Tool("test_related_files", "validation", "stable", true, false, "Find tests related to a set of changed files."),
        Tool("find_unused_symbols", "advanced-analysis", "stable", true, false, "Find likely unused symbols."),
        Tool("get_di_registrations", "advanced-analysis", "stable", true, false, "Inspect DI registration patterns in source."),
        Tool("get_complexity_metrics", "advanced-analysis", "stable", true, false, "Compute cyclomatic complexity and related metrics."),
        Tool("find_reflection_usages", "advanced-analysis", "stable", true, false, "Find reflection-heavy call sites."),
        Tool("trace_exception_flow", "advanced-analysis", "experimental", true, false, "Trace catch clauses that handle a given exception type."),
        Tool("get_namespace_dependencies", "advanced-analysis", "stable", true, false, "Build namespace dependency graphs."),
        Tool("get_nuget_dependencies", "advanced-analysis", "stable", true, false, "Inspect NuGet package references and versions."),
        Tool("semantic_search", "advanced-analysis", "stable", true, false, "Run semantic search over symbols and declarations."),
        Tool("find_duplicated_methods", "advanced-analysis", "stable", true, false, "Find clusters of near-duplicate method bodies by AST-normalized hash."),
        Tool("find_duplicate_helpers", "advanced-analysis", "experimental", true, false, "Flag private/internal helper methods whose body duplicates a reachable BCL/NuGet symbol."),
        Tool("find_dead_locals", "advanced-analysis", "experimental", true, false, "Find method-local variables whose only write is not followed by any read."),
        Tool("find_dead_fields", "advanced-analysis", "experimental", true, false, "Find source-declared fields that are never read, never written, or never either."),
        Tool("symbol_impact_sweep", "analysis", "experimental", true, false, "Sweep downstream impact of a symbol change: references + switch-exhaustiveness diagnostics + mapper-suffix callsites."),
        Tool("test_reference_map", "validation", "experimental", true, false, "Statically map source symbols to test references; returns covered/uncovered symbol lists and a coverage percentage. Supports offset/limit pagination and projectName scoping."),
        Tool("validate_workspace", "validation", "experimental", true, false, "Composite post-edit validation: compile_check + project_diagnostics (errors) + test_related_files (+ optional test_run)."),
        Tool("validate_recent_git_changes", "validation", "experimental", true, false, "post-edit-validate-workspace-scoped-to-touched-files: auto-scoped validation companion that derives changedFilePaths from git status --porcelain, falls back to full-workspace scope with a warning when git is unavailable or the solution is outside a git repo."),
        Tool("test_coverage", "validation", "stable", false, false, "Run coverage collection for test execution."),
        Tool("find_consumers", "analysis", "stable", true, false, "Find all types that depend on a given type or interface, classified by dependency kind."),
        Tool("get_cohesion_metrics", "analysis", "stable", true, false, "Measure type cohesion via LCOM4 metrics, identifying independent method clusters."),
        Tool("get_coupling_metrics", "analysis", "stable", true, false, "Measure per-type afferent/efferent coupling + Martin's instability index."),
        Tool("preview_record_field_addition", "analysis", "experimental", true, false, "Pre-flight audit: every site impacted by adding a positional field to a record."),
        Tool("find_shared_members", "analysis", "stable", true, false, "Find private members used by multiple public methods to inform type extractions."),
        Tool("suggest_refactorings", "advanced-analysis", "stable", true, false, "Analyze the workspace and return ranked refactoring suggestions based on complexity, cohesion (LCOM4), and unused symbol detection. Each suggestion includes severity, target, and recommended tool sequence."),
        Tool("analyze_data_flow", "advanced-analysis", "stable", true, false, "Analyze variable flow through a code region: reads, writes, captures, always-assigned."),
        Tool("analyze_control_flow", "advanced-analysis", "stable", true, false, "Analyze control flow: entry/exit points, reachability, return statements."),
        Tool("compile_check", "validation", "stable", true, false, "Fast in-memory compilation check without invoking dotnet build."),
        Tool("list_analyzers", "analysis", "stable", true, false, "List all loaded analyzers and their diagnostic rules."),
        Tool("get_operations", "advanced-analysis", "stable", true, false, "Get the IOperation tree for behavioral analysis at a source position."),
        Tool("analyze_snippet", "analysis", "stable", true, false, "Analyze a C# code snippet in an ephemeral workspace without loading a solution."),
        Tool("verify_pragma_suppresses", "validation", "stable", true, false, "Verify an existing #pragma warning disable/restore pair covers a fire line."),
        Tool("find_duplicated_code", "advanced-analysis", "stable", true, false, "Alias for find_duplicated_methods (cross-MCP-server name compatibility)."),
        Tool("get_test_coverage_map", "validation", "stable", false, false, "Alias for test_coverage (cross-MCP-server name compatibility)."),
        Tool("semantic_grep", "analysis", "experimental", true, false, "Token-aware regex search over C# code (identifier / string / comment scopes)."),
    ];
}
